name: Build and test pandajs

on: [push, pull_request]

jobs:
  build_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install
          yarn add usb
      - run: yarn build
      - run: yarn test
